from datetime import datetime
from codereview.llm.base import BaseLLMProvider
from codereview.models import ReviewResult, Summary, Score, Issue, Suggestion, CodeContext

class MockProvider(BaseLLMProvider):
    def __init__(self, config):
        self.config = config

    def generate_review(self, code_context: CodeContext) -> ReviewResult:
        # Generate a dummy review result based on content
        lines = code_context.source_code.split('\n')
        first_line = lines[0] if lines else ""
        
        return ReviewResult(
            summary=Summary(
                total_issues=1,
                critical_issues=0,
                high_issues=0,
                medium_issues=0,
                low_issues=1,
                summary_text="Mock review completed successfully. One mock styling issue found."
            ),
            score=Score(
                overall_score=85.0,
                security_score=100.0,
                performance_score=90.0,
                style_score=65.0
            ),
            issues=[
                Issue(
                    title="Mock Styling Issue",
                    description="This is a mock issue generated by the MockProvider for testing.",
                    severity="low",
                    category="style",
                    line_number=1,
                    code_snippet=first_line,
                    suggestion=Suggestion(
                        original_code=first_line,
                        proposed_code=f"# Verified: {first_line}",
                        explanation="This is a dummy improvement suggestion."
                    )
                )
            ],
            timestamp=datetime.utcnow().isoformat() + "Z"
        )
